const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
const { NextRequest } = require('next/server');
const root = process.argv[2];
process.chdir(root);
process.env.NEXT_PUBLIC_SUPABASE_URL = '';
process.env.META_APP_ID = '123';
process.env.META_APP_SECRET = 'test-app-secret';
process.env.META_OAUTH_REDIRECT_URI = 'http://localhost:3000/api/facebook/oauth/callback';
process.env.META_GRAPH_API_VERSION = 'v26.0';
process.env.META_TOKEN_ENCRYPTION_KEY = 'ab'.repeat(32);
const lib = require(root + '/compiled/lib/facebook-connection.js');
let user = { id: 'owner-a', name: 'A', accessRole: 'employee', mustChangePassword: false };
let session = 'private-session-a';
const authPath = require.resolve(root + '/compiled/lib/auth.js');
require.cache[authPath] = { id: authPath, filename: authPath, loaded: true, exports: { currentUser: async () => user, currentToken: async () => session } };
const start = require(root + '/compiled/app/api/facebook/oauth/start/route.js');
const callback = require(root + '/compiled/app/api/facebook/oauth/callback/route.js');
const connection = require(root + '/compiled/app/api/facebook/connection/route.js');
const pages = require(root + '/compiled/app/api/facebook/pages/route.js');
const ads = require(root + '/compiled/app/api/ads/route.js');
let calls = [];
const reply = body => new Response(JSON.stringify(body));
global.fetch = async (url, options) => {
  const u = new URL(url); calls.push(u.pathname);
  if (u.pathname.endsWith('/oauth/access_token')) return reply({ access_token: u.searchParams.has('fb_exchange_token') ? 'long-private-token' : 'short-private-token', expires_in: 3600 });
  assert.equal(options.headers.Authorization, 'Bearer long-private-token');
  if (u.pathname.endsWith('/me')) return reply({ id: 'fb-id', name: 'Facebook Test' });
  if (u.pathname.endsWith('/me/adaccounts')) return reply({ data: [{ id: 'act_123', name: 'Own account', currency: 'VND' }] });
  throw new Error('Unexpected request');
};
const request = (route, options = {}) => new NextRequest('http://localhost:3000' + route, options);
(async () => {
  const cipher = lib.encryptFacebookSecret('secret-token', 'owner-a');
  assert.ok(!cipher.includes('secret-token'));
  assert.equal(lib.decryptFacebookSecret(cipher, 'owner-a'), 'secret-token');
  assert.throws(() => lib.decryptFacebookSecret(cipher, 'owner-b'));
  assert.throws(() => lib.decryptFacebookSecret(cipher.slice(0, -2) + 'AA', 'owner-a'));
  const state = lib.makeFacebookState('owner-a', session);
  assert.equal(lib.verifyFacebookState(state.cookie, state.state, 'owner-a', session), true);
  assert.equal(lib.verifyFacebookState(state.cookie, state.state, 'owner-b', session), false);
  assert.equal(lib.verifyFacebookState(state.cookie, state.state, 'owner-a', 'another-session'), false);
  assert.equal(lib.verifyFacebookState(state.cookie, 'invalid', 'owner-a', session), false);
  const expiredState = lib.encryptFacebookSecret(JSON.stringify({ state: state.state, userId: 'owner-a', session: lib.sessionFingerprint(session), createdAt: Date.now() - 601000 }), 'facebook-oauth-state');
  assert.equal(lib.verifyFacebookState(expiredState, state.state, 'owner-a', session), false);
  assert.equal((await start.POST(request('/api/facebook/oauth/start', { method: 'POST', headers: { origin: 'https://evil.example' } }))).status, 403);
  const login = await start.POST(request('/api/facebook/oauth/start', { method: 'POST', headers: { origin: 'http://localhost:3000' } }));
  assert.equal(login.status, 200);
  const authorize = new URL((await login.json()).url);
  assert.equal(authorize.hostname, 'www.facebook.com');
  const cookie = login.cookies.get(lib.FACEBOOK_STATE_COOKIE).value;
  const cookieHeader = `${lib.FACEBOOK_STATE_COOKIE}=${cookie}`;
  const denied = await callback.GET(request('/api/facebook/oauth/callback?state=invalid&code=malicious', { headers: { cookie: cookieHeader } }));
  assert.ok(denied.headers.get('location').endsWith('facebook=invalid_state'));
  assert.equal(calls.length, 0);
  const success = await callback.GET(request(`/api/facebook/oauth/callback?state=${authorize.searchParams.get('state')}&code=valid`, { headers: { cookie: cookieHeader } }));
  assert.ok(success.headers.get('location').endsWith('facebook=connected'));
  assert.equal(success.cookies.get(lib.FACEBOOK_STATE_COOKIE).value, '');
  const status = await connection.GET();
  const statusBody = await status.json();
  assert.equal(statusBody.connected, true);
  assert.ok(!JSON.stringify(statusBody).includes('private-token'));
  assert.equal((await lib.facebookCredentials('owner-a')).token, 'long-private-token');
  await assert.rejects(lib.facebookCredentials('owner-b'), lib.FacebookConnectionRequired);
  const store = await fs.readFile(path.join(root, '.data/workspace.json'), 'utf8');
  assert.ok(!store.includes('long-private-token'));
  const notOwned = await ads.GET(request('/api/ads?since=2026-09-01&until=2026-09-28&account=999'));
  assert.equal(notOwned.status, 403);
  assert.ok(!calls.some(call => call.includes('act_999')));
  user = { ...user, id: 'owner-b' };
  assert.equal((await pages.GET(request('/api/facebook/pages'))).status, 409);
  user = null;
  assert.equal((await start.POST(request('/api/facebook/oauth/start', { method: 'POST' }))).status, 401);
  assert.equal((await pages.GET(request('/api/facebook/pages'))).status, 401);
  assert.equal((await connection.GET()).status, 401);
  user = { id: 'owner-a', accessRole: 'employee', mustChangePassword: true };
  assert.equal((await pages.GET(request('/api/facebook/pages'))).status, 403);
  user.mustChangePassword = false;
  assert.equal((await connection.DELETE(request('/api/facebook/connection', { method: 'DELETE', headers: { origin: 'https://evil.example' } }))).status, 403);
  assert.equal((await connection.DELETE(request('/api/facebook/connection', { method: 'DELETE', headers: { origin: 'http://localhost:3000' } }))).status, 200);
  await assert.rejects(lib.facebookCredentials('owner-a'), lib.FacebookConnectionRequired);
  console.log('Facebook OAuth tests passed: state/session binding, CSRF, code exchange, encryption, per-user isolation, permissions, account ownership, and disconnect.');
})().catch(error => { console.error(error); process.exitCode = 1; });
