const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs/promises');
const root = process.argv[2];
// Isolated storage and no credentials: never read or mutate the real workspace.
for (const key of Object.keys(process.env)) if (key.includes('SUPABASE')) delete process.env[key];
process.chdir(root);
const repo = require(path.join(root, 'compiled/workspace-repository.js'));
const store = require(path.join(root, 'compiled/workspace-store.js'));
const state = require(path.join(root, 'compiled/notification-state.js'));
const { requestJson, RequestError } = require(path.join(root, 'compiled/client-request.js'));
(async () => {
  const member = await repo.createMember({name:'Test Owner', role:'QA', username:'qa.owner', password:'test-only-password', workType:'inhouse', accessRole:'admin'});
  const input = {title:'Concurrent task', owner:member.name, workType:'inhouse', status:'todo', startDate:'2026-09-25', deadline:'2026-09-25', startTime:'09:00', endTime:'11:00', format:'', brief:''};
  const tasks = await Promise.all(Array.from({length:45}, (_,i) => repo.createTask({...input,title:`Task ${i}`})));
  assert.equal((await repo.listTasks()).length,45);
  assert.equal(new Set(tasks.map(t=>t.code)).size,45);
  await Promise.all([repo.updateTask(tasks[0].id,{status:'completed'}),repo.updateTask(tasks[0].id,{title:'Updated title'})]);
  const task = (await repo.listTasks()).find(t=>t.id===tasks[0].id);
  assert.equal(task.status,'completed'); assert.equal(task.title,'Updated title');
  let feed = await repo.getNotificationFeed(member.id);
  assert.equal(feed.notifications.length,40); assert.equal(feed.unreadCount,45);
  const id = feed.notifications[0].id;
  const optimistic = state.readNotificationInFeed(feed,id);
  assert.equal(optimistic.unreadCount,44);
  assert.equal(state.readNotificationInFeed(optimistic,id).unreadCount,44);
  assert.equal(state.readAllNotificationsInFeed(feed).unreadCount,0);
  assert.equal(state.notificationDocumentTitle('(2) (4) K-MKT',45),'(45) K-MKT');
  assert.equal(state.notificationDocumentTitle('(45) K-MKT',0),'K-MKT');
  assert.equal(await repo.remindNotification('another-user',id),null);
  await repo.markNotificationRead(member.id,id);
  const reminders = await Promise.allSettled([repo.remindNotification(member.id,id),repo.remindNotification(member.id,id)]);
  assert.equal(reminders.filter(r=>r.status==='fulfilled').length,1);
  assert(reminders.find(r=>r.status==='rejected').reason instanceof repo.NotificationReminderCooldownError);
  assert.equal((await repo.getNotificationFeed(member.id)).unreadCount,45);
  const notification = (await repo.getNotificationFeed(member.id)).notifications.find(n=>n.id===id);
  assert.equal(state.reminderRetryAfter(notification,Date.parse(notification.remindedAt)),120);
  await repo.remindNotification(member.id,id,new Date(Date.parse(notification.remindedAt)+120000));
  await repo.markAllNotificationsRead(member.id);
  assert.equal((await repo.getNotificationFeed(member.id)).unreadCount,0);
  const deadlines = await Promise.all([repo.createDeadlineReminders(new Date('2026-09-25T05:00:00Z')),repo.createDeadlineReminders(new Date('2026-09-25T05:00:00Z'))]);
  assert.equal(deadlines.flat().length,44);
  await Promise.all(Array.from({length:10},(_,i)=>repo.savePushSubscription(member.id,{endpoint:`https://example.test/${i}`,keys:{p256dh:'test',auth:'test'}})));
  assert.equal((await repo.listPushSubscriptions([member.id])).length,10);
  // One task may belong to two people, while its type stays independent of their profiles.
  const colleague = await repo.createMember({name:'Second Owner', role:'Editor', username:'second.owner', password:'test-only-password', workType:'inhouse', accessRole:'employee'});
  const multi = await repo.createTask({...input, title:'Shared outsource work', workType:'outsource', status:'completed', assigneeIds:[member.id,colleague.id]});
  assert.deepEqual(multi.assigneeIds,[member.id,colleague.id]);
  assert.equal(multi.workType,'outsource');
  assert.equal(multi.owner,'Test Owner, Second Owner');
  const workload = require(path.join(root,'compiled/workload.js'));
  assert.equal(workload.assessWorkload(await repo.listTasks(),await repo.listMembers()).find(item=>item.member.id===colleague.id).totalTasks,1);
  assert.equal((await repo.getNotificationFeed(colleague.id)).unreadCount,1);
  await repo.updateMember(colleague.id,{name:'Renamed Owner',role:'Editor',username:'second.owner',password:'',workType:'outsource',accessRole:'employee'});
  let shared = (await repo.listTasks()).find(item=>item.id===multi.id);
  assert.equal(shared.owner,'Test Owner, Renamed Owner');
  assert.equal(shared.workType,'outsource');
  const inhouseForOutsourceMember = await repo.createTask({...input, title:'Internal work with external-profile member', owner:'Chưa phân công', assigneeIds:[colleague.id], workType:'inhouse'});
  assert.equal(inhouseForOutsourceMember.workType,'inhouse');
  await repo.updateMember(colleague.id,{name:'Renamed Owner',role:'Editor',username:'second.owner',password:'',workType:'inhouse',accessRole:'employee'});
  assert.equal((await repo.listTasks()).find(item=>item.id===inhouseForOutsourceMember.id).workType,'inhouse');
  const newlyAssigned = await repo.createTask({...input, title:'Assign later', owner:'Chưa phân công', assigneeIds:[], workType:'outsource'});
  assert.equal(newlyAssigned.assigneeIds.length,0);
  const assignedLater = await repo.updateTask(newlyAssigned.id,{assigneeIds:[colleague.id]});
  assert.equal(assignedLater.owner,'Renamed Owner');
  assert.equal(assignedLater.workType,'outsource');
  assert.equal((await repo.getNotificationFeed(colleague.id)).unreadCount,3);
  await repo.deleteMember(colleague.id);
  shared = (await repo.listTasks()).find(item=>item.id===multi.id);
  assert.deepEqual(shared.assigneeIds,[member.id]);
  assert.equal(shared.owner,'Test Owner');
  const scheduledTask = await repo.createTask({...input,title:'Scheduled work',assigneeIds:[member.id],reminderDate:'2026-09-25',reminderTime:'15:00',reminderRepeat:'daily'});
  assert.equal(scheduledTask.reminderTime,'15:00');
  assert.equal((await repo.createScheduledReminders(new Date('2026-09-25T07:59:00Z'))).length,0);
  assert.equal((await repo.createScheduledReminders(new Date('2026-09-25T08:00:00Z'))).filter(item=>item.eventKey.includes(scheduledTask.id)).length,1);
  assert.equal((await repo.createScheduledReminders(new Date('2026-09-25T08:01:00Z'))).filter(item=>item.eventKey.includes(scheduledTask.id)).length,0);
  assert.equal((await repo.createScheduledReminders(new Date('2026-09-26T08:00:00Z'))).filter(item=>item.eventKey.includes(scheduledTask.id)).length,0);
  await repo.scheduleNotification(member.id,id,'2026-09-26T08:00:00.000Z','daily',new Date('2026-09-25T08:00:00Z'));
  assert.equal((await repo.createScheduledReminders(new Date('2026-09-26T07:59:00Z'))).length,0);
  const scheduledNotifications = await repo.createScheduledReminders(new Date('2026-09-26T08:00:00Z'));
  assert.equal(scheduledNotifications.filter(item=>item.id===id).length,1);
  assert.equal((await repo.createScheduledReminders(new Date('2026-09-26T08:01:00Z'))).length,0);
  assert.equal((await repo.getNotificationFeed(member.id)).notifications.find(item=>item.id===id).scheduledAt,'2026-09-27T08:00:00.000Z');
  const before = await store.readWorkspace();
  await assert.rejects(store.withWorkspaceTransaction(async()=>{const data=await store.readWorkspace();data.tasks=[];await store.writeWorkspace(data);throw Error('rollback');}));
  assert.equal((await store.readWorkspace()).tasks.length,before.tasks.length);
  await fs.writeFile(path.join(root,'.data/workspace.json'),'{corrupt');
  await assert.rejects(store.readWorkspace());
  const originalFetch=global.fetch;
  global.fetch=async()=>new Response('unavailable',{status:503});
  await assert.rejects(requestJson('/test'),e=>e instanceof RequestError&&e.status===503);
  global.fetch=async()=>new Response(JSON.stringify({error:'Cooldown',retryAfter:120}),{status:429});
  await assert.rejects(requestJson('/test'),e=>e.status===429&&e.body.retryAfter===120);
  global.fetch=(_,init)=>new Promise((_,reject)=>init.signal.addEventListener('abort',()=>reject(new DOMException('Aborted','AbortError'))));
  await assert.rejects(requestJson('/test',{},5),e=>e.status===408);
  global.fetch=originalFetch;
  console.log('Workspace regressions passed: concurrent writes, unique task codes, patch merging, unread totals, read idempotency, cooldown, ownership, cron deduplication, push writes, transaction rollback, corrupted storage, network errors and timeout.');
})().catch(error=>{console.error(error);process.exitCode=1;});
